import = [
  # "~/.config/alacritty/bamboo.toml",
  # "~/.config/alacritty/kanagawa_wave.toml",
  "~/.config/alacritty/kanagawa_dragon.toml",
  # "~/.config/alacritty/kanagawa_lotus.toml",
  # "~/.config/alacritty/sonokai.toml",
  # "~/.config/alacritty/tokyonight.toml",
]


[cursor.style]
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 16

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"

[window.padding]
x = 18
y = 16

[window]
opacity = 0.85
dynamic_padding = false
decorations = "None"
