#!/bin/sh

# This script is used in conjunction with srandrd to automatically update
# xrandr outputs when my external monitor is connected/disconnected.

case "${SRANDRD_OUTPUT} ${SRANDRD_EVENT}" in
  "DP-1 connected") xrandr --dpi 150 --output eDP-1 --mode 1920x1080 --pos 0x1080 --scale 1x1 --rotate normal --output DP-1 --primary --mode 3840x2160 --pos 1920x0 --rotate normal && /usr/bin/i3-msg restart ;;
  "DP-1 disconnected") xrandr --output eDP-1 --auto --primary --output DP-1 --off && /usr/bin/i3-msg restart ;;
esac
