local impatient = require("impatient")
impatient.enable_profile()

require("plugin_conf.nvim_tree")
require("plugin_conf.neogit")
require("plugin_conf.neoscroll")
require("plugin_conf.todo")
require("plugin_conf.lualine")
require("plugin_conf.telescope")
require("plugin_conf.trouble")
require("plugin_conf.treesitter")
require("plugin_conf.lspsaga")
require("plugin_conf.lsp")
require("plugin_conf.dbg")
require("plugin_conf.cmp")
require("plugin_conf.git")
require("plugin_conf.gitsigns")
require("plugin_conf.neorg")
require("plugin_conf.indent_blankline")
require("plugin_conf.which_key")
require("plugin_conf.bufferline")
require("plugin_conf.comment")
require("plugin_conf.toggleterm")
require("plugin_conf.zen")
require("plugin_conf.autopairs")
-- comment out until https://github.com/neovim/neovim/issues/11440 is resolved
-- require("plugin_conf.shade")
-- require("plugin_conf.alpha")

-- easy installs
require("nvim-web-devicons").setup({ default = true })
require("colorizer").setup()
require("stabilize").setup()
require("renamer").setup({})
require("nvim-ts-autotag").setup()
require("treesitter-context").setup({})
require("fidget").setup({})

vim.g.do_filetype_lua = 1

vim.keymap.set("n", "<leader>tm", ":TableModeToggle<cr>")
vim.keymap.set("n", "<leader>dfo", ":DiffviewOpen<cr>")
vim.keymap.set("n", "<leader>dfc", ":DiffviewClose<cr>")
vim.keymap.set("n", "<leader>hw", ":HopWord<cr>")
