# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

[config]
# plugins_dir = "plugins/*"
auto_setup = false

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.42.1"
neorg = "9.1.1"
"rocks-git.nvim" = "2.5.1"
"rocks-config.nvim" = "3.0.0"
"rocks-treesitter.nvim" = "1.2.0"
tree-sitter-toml = "0.0.30"
tree-sitter-haskell = "scm"
"haskell-tools.nvim" = "4.3.1"
tree-sitter-json = "scm"
"which-key.nvim" = "3.13.3"
"telescope.nvim" = "scm"
"oil.nvim" = "2.13.0"
"toggleterm.nvim" = "2.13.0"
fzf-lua = "0.0.1483"
"hover.nvim" = "scm"
"gitsigns.nvim" = "0.9.0"
"diffview.nvim" = "scm"
"conform.nvim" = "8.2.0"
nvim-lint = "scm"
nvim-cmp = "scm"
"kanagawa.nvim" = "scm"
"heirline.nvim" = "1.0.7"
"overseer.nvim" = "1.5.0"
nvim-dap = "0.8.0"
"mason.nvim" = "1.10.0"
luasnip = "2.3.0"
"haskell-snippets.nvim" = "1.4.4"
nvim-ufo = "1.4.0"
nvim-web-devicons = "0.100"
tree-sitter-lua = "scm"
nvim-lspconfig = "1.0.0"
"mason-lspconfig.nvim" = "1.31.0"
"transparent.nvim" = { git = "xiyaowong/transparent.nvim" }
"tiny-inline-diagnostic.nvim" = { git= "rachartier/tiny-inline-diagnostic.nvim" }
"outline.nvim" = { git = "https://git.sr.ht/~hedy/outline.nvim" }
cmp-buffer = "scm"
cmp-nvim-lsp = "scm"
cmp-path = "scm"
cmp-cmdline = "scm"
nvim-autopairs = "scm"
"neoscroll.nvim" = "0.2.0"
"rest.nvim" = "3.8.4"
tree-sitter-http = "scm"
neogit = "1.0.0"
tree-sitter-elixir = "0.0.34"
tree-sitter-heex = "0.0.30"
tree-sitter-css = "0.0.31"
"elixir-tools.nvim" = "0.16.1"
"dressing.nvim" = "3.1.0"
nvim-highlight-colors = { git = "brenoprata10/nvim-highlight-colors" }
"tailwind-tools.nvim"= { git = "luckasRanarison/tailwind-tools.nvim" }
"avante.nvim" = { git = "yetone/avante.nvim" }
tree-sitter-html = "0.0.33"
tree-sitter-tsx = "0.0.31"
nvim-surround = "2.1.5"


[bundles]
colors.items = [
  "kanagawa.nvim",
  "heirline.nvim"
]
lsp.items = [
  "nvim-lspconfig",
  "mason.nvim",
  "mason-lspconfig.nvim"
]
