# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

[config]
# plugins_dir = "plugins/*"
auto_setup = false

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.40.2"
neorg = "9.1.1"
"rocks-git.nvim" = "2.3.1"
"rocks-config.nvim" = "3.0.0"
"rocks-treesitter.nvim" = "1.1.3"
tree-sitter-toml = "0.0.17"
tree-sitter-haskell = "scm"
"haskell-tools.nvim" = "4.1.0"
tree-sitter-typescript = "scm"
tree-sitter-json = "scm"
"which-key.nvim" = "3.13.3"
"telescope.nvim" = "scm"
"oil.nvim" = "2.12.2"
"toggleterm.nvim" = "2.12.0"
fzf-lua = "0.0.1458"
"hover.nvim" = "scm"
"gitsigns.nvim" = "0.9.0"
"diffview.nvim" = "scm"
"conform.nvim" = "8.1.0"
nvim-lint = "scm"
nvim-cmp = "scm"
"kanagawa.nvim" = "scm"
"heirline.nvim" = "1.0.6"
"overseer.nvim" = "1.4.0"
nvim-dap = "0.8.0"
"mason.nvim" = "1.10.0"
luasnip = "2.3.0"
"haskell-snippets.nvim" = "1.4.4"
nvim-ufo = "1.4.0"
nvim-web-devicons = "0.100"
tree-sitter-lua = "scm"
nvim-lspconfig = "1.0.0"
"mason-lspconfig.nvim" = "1.31.0"
"transparent.nvim" = "8a2749a2fa74f97fe6557f61b89ac7fd873f3c21"
"tiny-inline-diagnostic.nvim" = "1a83e7ce5c9d0ae4d89fc5c812b55ff8ed1d39e7"
"outline.nvim" = "scm"
cmp-buffer = "scm"
cmp-nvim-lsp = "scm"
cmp-path = "scm"
cmp-cmdline = "scm"
nvim-autopairs = "scm"
"neoscroll.nvim" = "0.2.0"
"rest.nvim" = "3.8.0"
tree-sitter-http = "scm"
neogit = "1.0.0"
tree-sitter-elixir = "0.0.18"
tree-sitter-heex = "0.0.17"
tree-sitter-css = "0.0.17"
"elixir-tools.nvim" = "0.16.0"
"dressing.nvim" = "3.0.0"
nvim-highlight-colors= "scm"
"tailwind-tools.nvim"= "v0.3.1"
"avante.nvim"= "v0.0.2"
tree-sitter-html = "0.0.17"
tree-sitter-tsx = "0.0.17"


[bundles]
colors.items = [
  "kanagawa.nvim",
  "heirline.nvim"
]
lsp.items = [
  "nvim-lspconfig",
  "mason.nvim",
  "mason-lspconfig.nvim"
]
